export const FavGame = [
  { value: 'Favorite Game', label: 'Favorite Game'},
  { value: 'PUBG', label: 'PUBG'},
  { value: 'Dota 2', label: 'Dota 2' },
  { value: 'Valorant', label: 'Valorant'},
  { value: 'Overwatch 2', label: 'Overwatch 2' },
  { value: 'Call of Duty', label: 'Call of Duty'},
  { value: 'PUBG', label: 'PUBG'},
  { value: 'Dota 2', label: 'Dota 2' },
  { value: 'Valorant', label: 'Valorant'},
];

export const RoleOptions = [
  { value: 'Role', label: 'Role'},
  { value: 'Player', label: 'Player'},
  { value: 'Referee', label: 'Referee'},
  { value: 'Couch', label: 'Couch'},
  { value: 'Team Manager', label: 'Team Manager'},
  { value: 'Club admin', label: 'Club admin'},
  { value: 'Analyst', label: 'Analyst'},
  { value: 'Caster', label: 'Caster'},
  { value: 'Media outlet', label: 'Media outlet'},
  { value: 'Video Editor', label: 'Video Editor'},
  { value: 'Grapich Disinger', label: 'Grapich Disinger'},
  { value: 'Streamer', label: 'Streamer'},
  { value: 'Frontend creator', label: 'Frontend creator'},
  { value: 'Game developer ', label: 'Game developer '},
  { value: 'Tournament Organizer', label: 'Tournament Organizer'},
  { value: 'Club Owner', label: 'Club Owner'},
];
